Vegan pizza.md
=> Created a Vegan Pizza

pizzas/class-of-2022/QuattroFunghi.md
Forgot to include #1 in my commit message.
=> added some mushroom goodness pizza #1

pizzas/pepperLove.md
=> #1 New pizza

pizzas/Mediterranean Pizza.md
added Mediterranean Pizza :pizza:
=> Create Mediterranean Pizza.md #1

pizzas/White_Swan.md
Changed pizza name and ingredients
=> Changed pizza name #1

pizzas/Hot pizza.md
Added my favourite  hot hot pizza !
=> Added pizza name #1

pizzas/GOAT - Copy - kopia.md
Changed pizza name #1 and ingredients.
=> Create GOAT - Copy - kopia.md

pizzas/No clue but it is good.md
=> added No clue #1

pizzas/Thomas Pizza/Git Test.md
=> #1 Thomas Pizza

pizzas/Chicken Garlic Pizza.md
=> added Chicken Garlic Pizza #1

pizzas/countrypizza.md
A new proposal for the party menu!
=> Create the Country Pizza for issue #1

pizzas/Ham, pepper and egg pizza.md, pizzas/avocado - Copy.md
I have added the ingredients for a ham, pepper and egg pizza
=> #1 Ham, pepper and egg pizza creation

pizzas/Chanterelle pizza.md
=> #1 Create Chanterelle pizza.md

pizzas/pollo al banana.md
#1 Added a chicken pizza for your delight!
=> Created pollo al banana.md

pizzas/Noah special.md
=> Added Noah special recipe

pizzas/Chanterelle pizza.md, pizzas/Dessert pizza.md
=> #1 Dessert pizza

pizzas/GOAT.md, pizzas/Sofiapizza.md
#1 So I added a pizza. I think I got it right in the end, but the changes I comitted at first were not meant to be comitted... 
Is it possible to accept the most recently changes I did/comitted, not the ones I did last week? 
/Sofia
=> About the pizza made today 

pizzas/Pizzaladiere.md
=> Pizzaladiere.md

pizzas/class-of-2024/Pizza Wermland.md
Adding my #1 Pizza Wermland to learn about GitHub.
=> #1 Pizza Wermland

pizzas/goat.md
=> added more #1

pizzas/class-of-2024/# Ems Pizza.md
=> Create # Ems Pizza.md

pizzas/goat (kopia).md, pizzas/sandrasGoat.md
=> New improved GOAT

pizzas/TacoPizza.md
=> Added Taco Pizza 

pizzas/Jessicaspizza.md
=> jessicaspizza

pizzas/goat - kopia.md, pizzas/vera.md
=> Added Vera

pizzas/potato potahto.md, pizzas/potato potato.md
=> Potato Potahto

pizzas/SugarIsGoodForYou.md
=> Sugar is really good for you

pizzas/Marinara.md
=> Added Marinara pizza

pizzas/Stigtomtapizza.md
#1 Added Stigtomtapizza. Try this out!
=> Added Stigtomtapizza.md

pizzas/I have the (moral) high ground.md
a vegan pizza as per request #102, and #1
=> Added "I have the (moral) high ground"
